// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVJbjTZowj8cogHUHw-iZviL5yS_G43WI',
    appId: '1:980088408492:web:f8a3b1159797c156305209',
    messagingSenderId: '980088408492',
    projectId: 'aurox-29ccf',
    authDomain: 'aurox-29ccf.firebaseapp.com',
    storageBucket: 'aurox-29ccf.firebasestorage.app',
    measurementId: 'G-K6D1C207YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUUDHo62vlwnbaLAEOPDpp2JGAJ06onw',
    appId: '1:980088408492:android:50490d330c3908b7305209',
    messagingSenderId: '980088408492',
    projectId: 'aurox-29ccf',
    storageBucket: 'aurox-29ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPhs1lXrQX-8DZzP7rU0-aayjR8p_gx4',
    appId: '1:980088408492:ios:29f82d569fc633b6305209',
    messagingSenderId: '980088408492',
    projectId: 'aurox-29ccf',
    storageBucket: 'aurox-29ccf.firebasestorage.app',
    iosBundleId: 'com.example.aurox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPhs1lXrQX-8DZzP7rU0-aayjR8p_gx4',
    appId: '1:980088408492:ios:29f82d569fc633b6305209',
    messagingSenderId: '980088408492',
    projectId: 'aurox-29ccf',
    storageBucket: 'aurox-29ccf.firebasestorage.app',
    iosBundleId: 'com.example.aurox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVJbjTZowj8cogHUHw-iZviL5yS_G43WI',
    appId: '1:980088408492:web:22d7112b04ab1378305209',
    messagingSenderId: '980088408492',
    projectId: 'aurox-29ccf',
    authDomain: 'aurox-29ccf.firebaseapp.com',
    storageBucket: 'aurox-29ccf.firebasestorage.app',
    measurementId: 'G-V7D30BY9SE',
  );
}
